// // Try, catch, finally
// try {
//     let x = undefined;
//     console.log(x[0]);
// } catch (err) {
//     console.log("Error handling in catch", err);
// } finally {
//     console.log("finally always gets executed");
// }
// console.log("end");

// // Use of Try Catch in Real World Application
// try {
//     console.log("hello");
//     console.log(a);
//     console.log("ending try");
// } catch {
//     console.log("handled");
// }finally{
//     console.log("finally");
// }
// console.log("end");

// Defining a Class, Class Instantiation
